import * as sx from "@stylexjs/stylex";

export const styles = sx.create({
  wrapper: {
    backgroundColor: "var(--surface)",
    boxSizing: "border-box",
    minHeight: "100vh",
    width: "100%",
  },
  root: {
    boxSizing: "border-box",
    color: "var(--text-color)",
    fontFamily: "var(--font-family)",
    marginInline: "auto",
    maxWidth: "1120px",
    padding: {
      default: "var(--space-600) var(--space-800) var(--space-800)",
      "@media (max-width: 1024px)": "var(--space-600) var(--space-600) var(--space-600)",
      "@media (max-width: 768px)": "var(--space-500) var(--space-400) var(--space-500)",
      "@media (max-width: 480px)": "var(--space-400) var(--space-300) var(--space-400)",
    },
    width: "100%",
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-200)",
    maxWidth: "72ch",
  },
  h1: { marginBottom: "var(--space-100)" },
  h2: { marginBottom: "var(--space-300)" },
  h3: { marginBottom: "var(--space-200)" },
  platformSelect: {
    appearance: "none",
    backgroundColor: "var(--form-background)",
    backgroundImage:
      "linear-gradient(45deg, transparent 50%, currentColor 50%), linear-gradient(135deg, currentColor 50%, transparent 50%)",
    backgroundPosition: "calc(100% - 15px) 50%, calc(100% - 10px) 50%",
    backgroundRepeat: "no-repeat",
    backgroundSize: "5px 5px, 5px 5px",
    borderColor: "var(--form-default-border)",
    borderRadius: "var(--radius-200)",
    borderStyle: "solid",
    borderWidth: "var(--stroke-100)",
    color: "var(--form-default-text-color)",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: 600,
    minWidth: "16rem",
    paddingBlock: "var(--space-200)",
    paddingInlineEnd: "var(--space-500)",
    paddingInlineStart: "var(--space-300)",
  },
  downloadButton: { marginLeft: "auto" },
  code: {
    borderRadius: "8px",
    color: "var(--text-color)",
    fontFamily: "monospace",
    fontSize: "var(--font-size-50)",
    lineHeight: "var(--line-height-50)",
    margin: 0,
    overflowX: "auto",
    padding: "var(--space-000)",
  },
  colorGrid: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
  },
  baseGrid: {
    display: "grid",
    gap: "12px",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
  },
  tokenCard: {
    borderColor: "var(--border-color)",
    borderRadius: "var(--radius-300)",
    borderStyle: "solid",
    borderWidth: "var(--stroke-100)",
    overflow: "hidden",
  },
  swatch: { height: "60px" },
  whiteSwatch: {
    borderBottomColor: "var(--border-color)",
    borderBottomStyle: "solid",
    borderBottomWidth: "var(--stroke-100)",
    height: "60px",
  },
  colorSwatch: { height: "54px" },
  tokenMeta: { fontSize: "12px", padding: "10px" },
  compactTokenMeta: {
    fontSize: "12px",
    paddingBlock: "8px",
    paddingInline: "10px",
  },
  smallMeta: {
    color: "var(--text-color-secondary)",
    fontSize: "11px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  radiusName: { fontSize: "13px", fontWeight: 600 },
  radiusValue: { color: "var(--text-color-secondary)", fontSize: "12px" },
  tokenName: { fontWeight: 600 },
  typographyDetailsStack: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-500)",
  },
  spacingList: { display: "grid", gap: "12px" },
  spacingRow: {
    alignItems: "center",
    borderColor: "var(--border-color)",
    borderRadius: "var(--radius-200)",
    borderStyle: "solid",
    borderWidth: "var(--stroke-100)",
    display: "flex",
    gap: "16px",
    paddingBlock: "8px",
    paddingInline: "12px",
  },
  spacingName: { fontSize: "13px", fontWeight: 600, width: "120px" },
  spacingValue: {
    color: "var(--text-color-secondary)",
    fontSize: "13px",
    width: "80px",
  },
  spacingBar: {
    backgroundColor: "var(--grey-300)",
    borderRadius: "var(--radius-100)",
    height: "16px",
  },
  radiusGrid: {
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
  },
  radiusPreview: {
    backgroundColor: "var(--surface-200)",
    borderColor: "var(--grey-300)",
    borderStyle: "solid",
    borderWidth: "var(--stroke-200)",
    height: "60px",
    margin: "0 auto 8px auto",
    width: "60px",
  },
  preview: {
    maxWidth: "300px",
    overflow: "hidden",
    paddingBlock: "10px",
    paddingInline: "14px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  strokeBar: {
    backgroundColor: "var(--grey-900)",
    borderRadius: "var(--radius-100)",
    flex: 1,
  },
  speedGrid: {
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
  },
  speedName: { fontSize: "14px", fontWeight: 600, marginBottom: "4px" },
  speedValue: {
    color: "var(--text-color-secondary)",
    fontSize: "13px",
    marginBottom: "12px",
  },
  pulseFrame: {
    alignItems: "center",
    backgroundColor: "var(--surface)",
    borderColor: "var(--border-color)",
    borderRadius: "var(--radius-200)",
    borderStyle: "solid",
    borderWidth: "var(--stroke-100)",
    display: "flex",
    height: "56px",
    justifyContent: "center",
  },
  pulse: {
    backgroundColor: "var(--grey-300)",
    borderRadius: "var(--radius-100)",
    height: "28px",
    width: "28px",
  },
});
