import * as sx from "@stylexjs/stylex";

export const styles = sx.create({
  wrapper: {
    backgroundColor: "var(--surface)",
    boxSizing: "border-box",
    minHeight: "100vh",
    width: "100%",
  },
  root: {
    boxSizing: "border-box",
    color: "var(--text-color)",
    fontFamily: "var(--font-family)",
    marginInline: "auto",
    maxWidth: "1120px",
    padding: {
      default: "var(--space-600) var(--space-800) var(--space-800)",
      "@media (max-width: 1024px)": "var(--space-600) var(--space-600) var(--space-600)",
      "@media (max-width: 768px)": "var(--space-500) var(--space-400) var(--space-500)",
      "@media (max-width: 480px)": "var(--space-400) var(--space-300) var(--space-400)",
    },
    width: "100%",
  },
  sectionHeader: {
    display: "flex",
    flexDirection: "column",
    gap: "var(--space-200)",
    maxWidth: "72ch",
  },
  header: {
    borderBottom: "var(--stroke-100) solid var(--border-color)",
    marginBottom: "var(--space-300)",
    paddingBottom: "var(--space-200)",
  },
  headerStack: {
    alignItems: {
      default: "center",
      "@media (max-width: 600px)": "stretch",
    },
    display: "flex",
    flexDirection: {
      default: "row",
      "@media (max-width: 600px)": "column",
    },
    gap: "var(--space-400)",
    justifyContent: "space-between",
    width: "100%",
  },
  headerAction: {
    flexShrink: 0,
  },
  title: { marginBottom: "var(--space-100)" },
  description: {},
  surface: { marginTop: "var(--space-500)" },
  surfaceTitle: { marginBlockEnd: "var(--space-400)" },
  visualGrid: {
    display: "grid",
    gap: "var(--space-500)",
    gridTemplateColumns: "repeat(auto-fit, minmax(20rem, 1fr))",
  },
  visualCard: {
    backgroundColor: "var(--surface)",
    borderColor: "var(--border-color)",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "var(--stroke-100)",
    padding: "16px",
  },
  tokenName: { fontWeight: 600, overflowWrap: "anywhere" },
  secondaryCell: {
    color: "var(--text-color-secondary)",
    overflowWrap: "anywhere",
  },
  resolvedCell: { overflowWrap: "anywhere" },
  resolvedValue: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    maxWidth: "100%",
    minWidth: 0,
    overflow: "hidden",
  },
  truncatedValue: {
    display: "block",
    flex: "1 1 auto",
    maxWidth: "100%",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  colorSwatch: {
    borderColor: "var(--border-color)",
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "var(--stroke-100)",
    flex: "0 0 auto",
    height: "14px",
    width: "14px",
  },
});
