import * as sx from "@stylexjs/stylex";

export const styles = sx.create({
  box: { boxSizing: "border-box" },
  flex: { display: "flex" },
  directionRow: { flexDirection: "row" },
  directionColumn: { flexDirection: "column" },
  gap000: { gap: "var(--space-000)" },
  gap100: { gap: "var(--space-100)" },
  gap200: { gap: "var(--space-200)" },
  gap300: { gap: "var(--space-300)" },
  gap400: { gap: "var(--space-400)" },
  gap500: { gap: "var(--space-500)" },
  gap600: { gap: "var(--space-600)" },
  gap700: { gap: "var(--space-700)" },
  gap800: { gap: "var(--space-800)" },
  alignStart: { alignItems: "flex-start" },
  alignCenter: { alignItems: "center" },
  alignEnd: { alignItems: "flex-end" },
  alignStretch: { alignItems: "stretch" },
  alignBaseline: { alignItems: "baseline" },
  justifyStart: { justifyContent: "flex-start" },
  justifyCenter: { justifyContent: "center" },
  justifyEnd: { justifyContent: "flex-end" },
  justifyBetween: { justifyContent: "space-between" },
  justifyAround: { justifyContent: "space-around" },
  justifyEvenly: { justifyContent: "space-evenly" },
  wrapNowrap: { flexWrap: "nowrap" },
  wrapWrap: { flexWrap: "wrap" },
  wrapReverse: { flexWrap: "wrap-reverse" },
});
